theme = "Default"
default_source = "Nyaa"
download_client = "RunCommand"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client.command]
cmd = 'curl "{torrent}" > ~/{file}'
shell_cmd = "sh -c"

[client.qBittorrent]
base_url = "http://localhost:8080"

[source.nyaa]
base_url = "https://nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false
